[tool.poetry]
name = "openbb-reports"
version = "0.1.0"
description = "Reports extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_reports" }]

[tool.poetry.dependencies]
python = ">=3.9.21,<3.14"
openbb-core = "^1.4.8"
jinja2 = "^3.1.2"
matplotlib = "^3.7.2"
openbb-charting = "^2.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_core_extension"]
reports = "openbb_reports.reports_router:router"
